name: CI/CD service Backend

on:
  push:
    branches: [ ProjectService ]

jobs:
  #build-docker-image
  CI:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t chetouiiftikhar/frontoff-img:${{ github.sha }} .
      - name: Verify image build
        run: docker images
      - name: Tag image for latest deployment (optional)
        run: docker tag chetouiiftikhar/project-img:${{ github.sha }} chetouiiftikhar/project-img:latest

 # push-to-dockerhub:
  CD: 
    runs-on: self-hosted
    needs: CI
  
    steps:
      - name: Login to Docker Hub (requires secret)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Push image to Docker Hub
        run: docker push chetouiiftikhar/project-img:latest
